import { SITE } from "@/shared/config/site";
import { getComponents } from "@/shared/lib/registry";
import { getAllThoughts } from "@/shared/lib/thoughts";

export const dynamic = "force-static";

export async function GET() {
  const thoughts = await getAllThoughts();
  const components = getComponents();

  // Get English versions only to avoid duplicates
  const articles = thoughts
    .filter((t) => t.lang === "en")
    .toSorted(
      (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
    );

  const lines = [
    `# ${SITE.name}`,
    "",
    SITE.description,
    "",
    `Website: ${SITE.url}`,
    `GitHub: ${SITE.github}`,
    `Twitter: ${SITE.twitter}`,
    `LinkedIn: ${SITE.linkedin}`,
    "",
    "---",
    "",
    "# Articles",
    "",
  ];
  // Articles section
  for (const article of articles) {
    lines.push(`## ${article.title}`);
    lines.push(`URL: ${SITE.url}/thoughts/${article.slug}`);
    lines.push(`Description: ${article.description}`);
    lines.push(`Published: ${article.date}`);
    lines.push(`Tags: ${article.tags.join(", ")}`);
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("# Components");
  lines.push("");

  // Components section
  for (const component of components) {
    lines.push(`## ${component.name}`);
    lines.push(`URL: ${SITE.url}/components/${component.name}`);
    if (component.description) {
      lines.push(`Description: ${component.description}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("# Pages");
  lines.push("");
  lines.push(`Home: ${SITE.url}`);
  lines.push(`Thoughts (Blog): ${SITE.url}/thoughts`);
  lines.push(`Components Registry: ${SITE.url}/components`);
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("This file is automatically generated.");
  lines.push(`Last updated: ${new Date().toISOString()}`);

  return new Response(lines.join("\n"), {
    headers: {
      "Cache-Control": "max-age=3600, s-maxage=86400",
      "Content-Type": "text/plain; charset=utf-8",
    },
  });
}
