/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {
  "contribution-card": {
    name: "contribution-card",
    description: "contribution-card component.",
    type: "registry:component",
    files: [{
      path: "registry/components/contribution-card.tsx",
      type: "registry:component",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/contribution-card.tsx")
      const exportName = Object.keys(mod).find((key) => typeof mod[key] === "function" || typeof mod[key] === "object") || "contribution-card"
      return { default: mod.default || mod[exportName] }
    }),
    categories: [],
    meta: {},
  },
  "trigger-them-transition": {
    name: "trigger-them-transition",
    description: "trigger-them-transition lib.",
    type: "registry:lib",
    files: [{
      path: "registry/utils/trigger-them-transition.ts",
      type: "registry:lib",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/utils/trigger-them-transition.ts")
      const exportName = Object.keys(mod).find((key) => typeof mod[key] === "function" || typeof mod[key] === "object") || "trigger-them-transition"
      return { default: mod.default || mod[exportName] }
    }),
    categories: [],
    meta: {},
  },
}